# infra/cloud/aws/cfn-template.yaml
# CloudFormation template for a serverless infrastructure stack.

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Backend stack for the Visual Graph Programming.

Resources:
  # DynamoDB Database Table
  Visual_graph_programmingTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  # Lambda Function
  Visual_graph_programmingFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.lambda_handler
      Runtime: python3.11
      CodeUri: ./src
      Environment:
        Variables:
          TABLE_NAME: !Ref Visual_graph_programmingTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref Visual_graph_programmingTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /status
            Method: get
