// AUTO-GENERATED by scripts/generate-nav.mjs from docs/mkdocs.yml — do not edit by hand.
export interface NavLeaf {
  title: string;
  kind: "md";
  path: string;
  source: string;
}
export interface NavExternal {
  title: string;
  kind: "external";
  href: string;
}
export interface NavSection {
  title: string;
  kind: "section";
  children: NavNode[];
}
export type NavNode = NavLeaf | NavExternal | NavSection;

export const navTree: NavNode[] = [
  {
    "title": "Home",
    "kind": "md",
    "path": "/docs",
    "source": "docs/content/index.md"
  },
  {
    "title": "Architecture",
    "kind": "md",
    "path": "/architecture",
    "source": "docs/content/architecture.md"
  },
  {
    "title": "Modules",
    "kind": "section",
    "children": [
      {
        "title": "C++ Base Core",
        "kind": "md",
        "path": "/modules/base",
        "source": "docs/content/modules/base.md"
      },
      {
        "title": "Python Backend",
        "kind": "md",
        "path": "/modules/backend",
        "source": "docs/content/modules/backend.md"
      },
      {
        "title": "VS Code Extension",
        "kind": "md",
        "path": "/modules/extension",
        "source": "docs/content/modules/extension.md"
      },
      {
        "title": "Tauri App",
        "kind": "md",
        "path": "/modules/app",
        "source": "docs/content/modules/app.md"
      },
      {
        "title": "Unreal Engine Plugin",
        "kind": "md",
        "path": "/modules/plugin",
        "source": "docs/content/modules/plugin.md"
      }
    ]
  },
  {
    "title": "Building the Docs",
    "kind": "md",
    "path": "/building",
    "source": "docs/content/building.md"
  },
  {
    "title": "Codebase Guides",
    "kind": "section",
    "children": [
      {
        "title": "Repository Guide",
        "kind": "md",
        "path": "/repo/README",
        "source": "README.md"
      },
      {
        "title": "Contributing",
        "kind": "md",
        "path": "/repo/git/CONTRIBUTING",
        "source": "git/CONTRIBUTING.md"
      },
      {
        "title": "Development Container",
        "kind": "md",
        "path": "/repo/-devcontainer/README",
        "source": ".devcontainer/README.md"
      }
    ]
  },
  {
    "title": "Reference",
    "kind": "section",
    "children": [
      {
        "title": "Development",
        "kind": "md",
        "path": "/repo/docs/DEVELOPMENT",
        "source": "docs/DEVELOPMENT.md"
      },
      {
        "title": "Testing",
        "kind": "md",
        "path": "/repo/docs/TESTING",
        "source": "docs/TESTING.md"
      },
      {
        "title": "Dependency Policy",
        "kind": "md",
        "path": "/repo/docs/DEPENDENCY_POLICY",
        "source": "docs/DEPENDENCY_POLICY.md"
      },
      {
        "title": "Documentation Standards",
        "kind": "md",
        "path": "/repo/docs/DOCUMENTATION_STANDARDS",
        "source": "docs/DOCUMENTATION_STANDARDS.md"
      },
      {
        "title": "Glossary",
        "kind": "md",
        "path": "/repo/docs/GLOSSARY",
        "source": "docs/GLOSSARY.md"
      },
      {
        "title": "Troubleshooting",
        "kind": "md",
        "path": "/repo/docs/TROUBLESHOOTING",
        "source": "docs/TROUBLESHOOTING.md"
      },
      {
        "title": "Benchmarks",
        "kind": "md",
        "path": "/repo/docs/BENCHMARKS",
        "source": "docs/BENCHMARKS.md"
      }
    ]
  },
  {
    "title": "Infrastructure",
    "kind": "section",
    "children": [
      {
        "title": "Infrastructure Overview",
        "kind": "md",
        "path": "/repo/infra/README",
        "source": "infra/README.md"
      },
      {
        "title": "Docker",
        "kind": "md",
        "path": "/repo/infra/docker/README",
        "source": "infra/docker/README.md"
      },
      {
        "title": "Terraform",
        "kind": "md",
        "path": "/repo/infra/terraform/README",
        "source": "infra/terraform/README.md"
      },
      {
        "title": "Ansible",
        "kind": "md",
        "path": "/repo/infra/ansible/README",
        "source": "infra/ansible/README.md"
      },
      {
        "title": "Nginx",
        "kind": "md",
        "path": "/repo/infra/nginx/README",
        "source": "infra/nginx/README.md"
      }
    ]
  },
  {
    "title": "Roadmap",
    "kind": "section",
    "children": [
      {
        "title": "Roadmap",
        "kind": "md",
        "path": "/repo/docs/moon/ROADMAP",
        "source": "docs/moon/ROADMAP.md"
      },
      {
        "title": "Changelog",
        "kind": "md",
        "path": "/repo/docs/moon/CHANGELOG",
        "source": "docs/moon/CHANGELOG.md"
      },
      {
        "title": "Track A — Base",
        "kind": "md",
        "path": "/repo/docs/moon/roadmaps/base",
        "source": "docs/moon/roadmaps/base.md"
      },
      {
        "title": "Track A — Backend",
        "kind": "md",
        "path": "/repo/docs/moon/roadmaps/backend",
        "source": "docs/moon/roadmaps/backend.md"
      },
      {
        "title": "Track B — Extension",
        "kind": "md",
        "path": "/repo/docs/moon/roadmaps/extension",
        "source": "docs/moon/roadmaps/extension.md"
      },
      {
        "title": "Track C — Plugin",
        "kind": "md",
        "path": "/repo/docs/moon/roadmaps/plugin",
        "source": "docs/moon/roadmaps/plugin.md"
      },
      {
        "title": "Track D — App",
        "kind": "md",
        "path": "/repo/docs/moon/roadmaps/app",
        "source": "docs/moon/roadmaps/app.md"
      },
      {
        "title": "Cross-Cutting — CI & Automation",
        "kind": "md",
        "path": "/repo/docs/moon/roadmaps/ci_automation",
        "source": "docs/moon/roadmaps/ci_automation.md"
      }
    ]
  }
];

export const searchIndex: { title: string; path: string; source: string }[] = [
  {
    "title": "Home",
    "path": "/docs",
    "source": "docs/content/index.md"
  },
  {
    "title": "Architecture",
    "path": "/architecture",
    "source": "docs/content/architecture.md"
  },
  {
    "title": "C++ Base Core",
    "path": "/modules/base",
    "source": "docs/content/modules/base.md"
  },
  {
    "title": "Python Backend",
    "path": "/modules/backend",
    "source": "docs/content/modules/backend.md"
  },
  {
    "title": "VS Code Extension",
    "path": "/modules/extension",
    "source": "docs/content/modules/extension.md"
  },
  {
    "title": "Tauri App",
    "path": "/modules/app",
    "source": "docs/content/modules/app.md"
  },
  {
    "title": "Unreal Engine Plugin",
    "path": "/modules/plugin",
    "source": "docs/content/modules/plugin.md"
  },
  {
    "title": "Building the Docs",
    "path": "/building",
    "source": "docs/content/building.md"
  },
  {
    "title": "Repository Guide",
    "path": "/repo/README",
    "source": "README.md"
  },
  {
    "title": "Contributing",
    "path": "/repo/git/CONTRIBUTING",
    "source": "git/CONTRIBUTING.md"
  },
  {
    "title": "Development Container",
    "path": "/repo/-devcontainer/README",
    "source": ".devcontainer/README.md"
  },
  {
    "title": "Development",
    "path": "/repo/docs/DEVELOPMENT",
    "source": "docs/DEVELOPMENT.md"
  },
  {
    "title": "Testing",
    "path": "/repo/docs/TESTING",
    "source": "docs/TESTING.md"
  },
  {
    "title": "Dependency Policy",
    "path": "/repo/docs/DEPENDENCY_POLICY",
    "source": "docs/DEPENDENCY_POLICY.md"
  },
  {
    "title": "Documentation Standards",
    "path": "/repo/docs/DOCUMENTATION_STANDARDS",
    "source": "docs/DOCUMENTATION_STANDARDS.md"
  },
  {
    "title": "Glossary",
    "path": "/repo/docs/GLOSSARY",
    "source": "docs/GLOSSARY.md"
  },
  {
    "title": "Troubleshooting",
    "path": "/repo/docs/TROUBLESHOOTING",
    "source": "docs/TROUBLESHOOTING.md"
  },
  {
    "title": "Benchmarks",
    "path": "/repo/docs/BENCHMARKS",
    "source": "docs/BENCHMARKS.md"
  },
  {
    "title": "Infrastructure Overview",
    "path": "/repo/infra/README",
    "source": "infra/README.md"
  },
  {
    "title": "Docker",
    "path": "/repo/infra/docker/README",
    "source": "infra/docker/README.md"
  },
  {
    "title": "Terraform",
    "path": "/repo/infra/terraform/README",
    "source": "infra/terraform/README.md"
  },
  {
    "title": "Ansible",
    "path": "/repo/infra/ansible/README",
    "source": "infra/ansible/README.md"
  },
  {
    "title": "Nginx",
    "path": "/repo/infra/nginx/README",
    "source": "infra/nginx/README.md"
  },
  {
    "title": "Roadmap",
    "path": "/repo/docs/moon/ROADMAP",
    "source": "docs/moon/ROADMAP.md"
  },
  {
    "title": "Changelog",
    "path": "/repo/docs/moon/CHANGELOG",
    "source": "docs/moon/CHANGELOG.md"
  },
  {
    "title": "Track A — Base",
    "path": "/repo/docs/moon/roadmaps/base",
    "source": "docs/moon/roadmaps/base.md"
  },
  {
    "title": "Track A — Backend",
    "path": "/repo/docs/moon/roadmaps/backend",
    "source": "docs/moon/roadmaps/backend.md"
  },
  {
    "title": "Track B — Extension",
    "path": "/repo/docs/moon/roadmaps/extension",
    "source": "docs/moon/roadmaps/extension.md"
  },
  {
    "title": "Track C — Plugin",
    "path": "/repo/docs/moon/roadmaps/plugin",
    "source": "docs/moon/roadmaps/plugin.md"
  },
  {
    "title": "Track D — App",
    "path": "/repo/docs/moon/roadmaps/app",
    "source": "docs/moon/roadmaps/app.md"
  },
  {
    "title": "Cross-Cutting — CI & Automation",
    "path": "/repo/docs/moon/roadmaps/ci_automation",
    "source": "docs/moon/roadmaps/ci_automation.md"
  }
];
